package org.industrial.ontology.app.persistence;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.bson.Document;
import org.bson.types.ObjectId;
import org.industrial.ontology.domain.jackson.ObjectMapperProvider;

import javax.annotation.Nonnull;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Converts domain records to and from the Mongo documents of the collections that the legacy repositories wrote with
 * Jackson ({@code ProjectDetails}, {@code PrefixDeclarations}, {@code EntityCrudKitSettings},
 * {@code PerspectiveDescriptors}, {@code PerspectiveLayouts}, {@code Forms}, {@code FormSelectors}, {@code Tags},
 * {@code EntitySearchFilters}; docs/01 §5.3).
 * <p>
 * Those repositories stored {@code objectMapper.convertValue(record, Document.class)} through the raw driver, with the
 * mapper from the legacy {@code ObjectMapperProvider}. wp-domain's {@link ObjectMapperProvider} is configured the
 * same way and the domain records keep the legacy Jackson names, so converting the same way gives the same documents.
 * These documents are never mapped by Spring Data: their nested values carry Jackson type ids, one of which is even
 * called {@code _class} (the crud kit suffix settings), and Spring Data's own type hints would clash with them.
 * <p>
 * Unknown properties are ignored when reading, as in the legacy mapper. That covers both the server-generated
 * {@code ObjectId} of the collections whose records have no {@code _id}, and the {@code className} field that old
 * Morphia versions left behind.
 */
public final class JacksonDocumentMapper {

    private static final String ID = "_id";

    private final ObjectMapper objectMapper;

    public JacksonDocumentMapper() {
        this(new ObjectMapperProvider().get());
    }

    public JacksonDocumentMapper(@Nonnull ObjectMapper objectMapper) {
        this.objectMapper = checkNotNull(objectMapper);
    }

    @Nonnull
    public Document toDocument(@Nonnull Object record) {
        return objectMapper.convertValue(checkNotNull(record), Document.class);
    }

    @Nonnull
    public <T> T fromDocument(@Nonnull Document document, @Nonnull Class<T> type) {
        checkNotNull(document);
        if (document.get(ID) instanceof ObjectId) {
            // Generated by the server; no record maps it, and Jackson would otherwise serialise it as a bean first.
            document = new Document(document);
            document.remove(ID);
        }
        return objectMapper.convertValue(document, type);
    }
}
