package org.industrial.ontology.app.apikey;

import org.industrial.ontology.domain.core.ApiKey;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Converted from the legacy {@code ApiKeyHasher_TestCase}: keys are stored as the lower-case hex SHA-256 of their
 * UTF-8 bytes, so that keys generated by the legacy server keep working.
 */
class ApiKeyServiceTest {

    @Test
    void shouldHashApiKey() throws Exception {
        var bytes = MessageDigest.getInstance("SHA-256").digest("abcd".getBytes(StandardCharsets.UTF_8));

        assertThat(ApiKeyService.hash(ApiKey.valueOf("abcd"))).isEqualTo(HexFormat.of().formatHex(bytes))
                                                             .isEqualTo("88d4266fd4e6338d13b845fcf289579d"
                                                                                + "209c897823b9217da3e161936f031589");
    }
}
