/**
 * Generated by openapi-typescript from wp-server /v3/api-docs. Do not edit by hand.
 * Placeholder until P1-15: run `pnpm gen:api` against a running backend to regenerate.
 */
export interface paths {}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
