package org.industrial.ontology.app.apikey;

import com.google.common.hash.Hashing;
import org.industrial.ontology.app.access.AccessManager;
import org.industrial.ontology.app.apikey.persistence.UserApiKeyRepository;
import org.industrial.ontology.app.apikey.persistence.UserApiKeysDocument.ApiKeyRecord;
import org.industrial.ontology.app.error.WpException;
import org.industrial.ontology.domain.core.ApiKey;
import org.industrial.ontology.domain.core.ApiKeyId;
import org.industrial.ontology.domain.core.UserId;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nonnull;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;

import static com.google.common.base.Preconditions.checkArgument;
import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Ported from {@code edu.stanford.bmir.protege.web.server.api.ApiKeyManager} and {@code ApiKeyHasher}: API keys
 * for scripts and integrations ({@code Authorization: ApiKey <key>}, docs/01 §6).
 * <p>
 * A key is a random UUID. Only its SHA-256 hash is stored, unsalted as in the legacy application (a random UUID
 * needs no salt), so keys generated by the legacy server keep working. The key itself is shown once, when it is
 * generated, and cannot be recovered.
 * <p>
 * Methods that take a {@code caller} act for that user, on that user's own keys (docs/07 5.1-16); the others serve
 * authentication and the command line.
 */
public class ApiKeyService {

    private static final Logger logger = LoggerFactory.getLogger(ApiKeyService.class);

    private final UserApiKeyRepository repository;

    private final AccessManager accessManager;

    private final Clock clock;

    public ApiKeyService(@Nonnull UserApiKeyRepository repository,
                         @Nonnull AccessManager accessManager,
                         @Nonnull Clock clock) {
        this.repository = checkNotNull(repository);
        this.accessManager = checkNotNull(accessManager);
        this.clock = checkNotNull(clock);
    }

    /**
     * The stored form of a key: the SHA-256 hash of its UTF-8 bytes, lower-case hex (legacy {@code ApiKeyHasher}).
     */
    @Nonnull
    public static String hash(@Nonnull ApiKey apiKey) {
        return Hashing.sha256().hashString(apiKey.getKey(), StandardCharsets.UTF_8).toString();
    }

    // Authentication

    /**
     * The user the key belongs to, if any.
     */
    @Nonnull
    public Optional<UserId> getUserIdForApiKey(@Nonnull ApiKey apiKey) {
        return repository.getUserIdForApiKey(hash(apiKey));
    }

    // Command line

    /**
     * Generates a key for the user ({@code wp-cli generate-api-key}); the user need not have signed in yet, so that
     * keys can be made for integration accounts.
     *
     * @throws IllegalArgumentException for the guest user
     * @throws WpException              {@code INVALID_REQUEST} if the purpose is blank
     */
    @Nonnull
    public GeneratedApiKey generateApiKeyForUser(@Nonnull UserId userId, @Nonnull String purpose) {
        checkArgument(!userId.isGuest() && !userId.getUserName().isBlank(),
                      "Cannot generate an API key for '%s'", userId.getUserName());
        var checkedPurpose = checkPurpose(purpose);
        var apiKeyId = ApiKeyId.generateApiKeyId();
        var apiKey = ApiKey.generateApiKey();
        // Mongo stores dates in milliseconds; truncating keeps what is returned equal to what is read back.
        var createdAt = clock.instant().truncatedTo(ChronoUnit.MILLIS);
        repository.addApiKey(userId, new ApiKeyRecord(apiKeyId.getId(), hash(apiKey), createdAt, checkedPurpose));
        logger.info("Generated API key {} for {}", apiKeyId.getId(), userId.getUserName());
        return new GeneratedApiKey(apiKey, new ApiKeyDetails(apiKeyId, checkedPurpose, createdAt));
    }

    // Requests

    /**
     * The caller's keys, without the keys themselves.
     */
    @Nonnull
    public List<ApiKeyDetails> getApiKeys(@Nonnull UserId caller) {
        accessManager.requireSignedIn(caller);
        return repository.getApiKeys(caller)
                         .stream()
                         .map(record -> new ApiKeyDetails(record.getApiKeyId(), record.purpose(), record.createdAt()))
                         .toList();
    }

    /**
     * Generates a key for the caller.
     *
     * @throws WpException {@code INVALID_REQUEST} if the purpose is blank
     */
    @Nonnull
    public GeneratedApiKey generateApiKey(@Nonnull UserId caller, @Nonnull String purpose) {
        accessManager.requireSignedIn(caller);
        return generateApiKeyForUser(caller, purpose);
    }

    /**
     * Revokes one of the caller's keys; the key stops working at once.
     *
     * @throws WpException {@code API_KEY_NOT_FOUND} if the caller has no key with this id
     */
    public void revokeApiKey(@Nonnull UserId caller, @Nonnull ApiKeyId apiKeyId) {
        accessManager.requireSignedIn(caller);
        var owned = repository.getApiKeys(caller).stream().anyMatch(record -> record.getApiKeyId().equals(apiKeyId));
        if (!owned) {
            throw WpException.notFound("API_KEY_NOT_FOUND", "No API key " + apiKeyId.getId());
        }
        repository.dropApiKey(caller, apiKeyId);
        logger.info("Revoked API key {} of {}", apiKeyId.getId(), caller.getUserName());
    }

    private static String checkPurpose(String purpose) {
        var trimmed = checkNotNull(purpose).trim();
        if (trimmed.isEmpty()) {
            throw WpException.invalidRequest("An API key needs a purpose");
        }
        return trimmed;
    }
}
